// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0RSc9ykGAsuUaEMLzbmc6xUtiOqhE0dM',
    appId: '1:818624181889:web:c06c346e14fd3bc33fbf80',
    messagingSenderId: '818624181889',
    projectId: 'adhicine-3b5f5',
    authDomain: 'adhicine-3b5f5.firebaseapp.com',
    storageBucket: 'adhicine-3b5f5.firebasestorage.app',
    measurementId: 'G-XE46GZ2VCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfj3enNURMkUCfhcUQH-5PfgsQoYjtKXs',
    appId: '1:818624181889:android:9c2ca6232d7fc9b33fbf80',
    messagingSenderId: '818624181889',
    projectId: 'adhicine-3b5f5',
    storageBucket: 'adhicine-3b5f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRrIlUTmgAd_5RYEGlsq_XqGc7TnX0VVQ',
    appId: '1:818624181889:ios:202eec85d5a0a53b3fbf80',
    messagingSenderId: '818624181889',
    projectId: 'adhicine-3b5f5',
    storageBucket: 'adhicine-3b5f5.firebasestorage.app',
    iosBundleId: 'com.example.adhicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRrIlUTmgAd_5RYEGlsq_XqGc7TnX0VVQ',
    appId: '1:818624181889:ios:202eec85d5a0a53b3fbf80',
    messagingSenderId: '818624181889',
    projectId: 'adhicine-3b5f5',
    storageBucket: 'adhicine-3b5f5.firebasestorage.app',
    iosBundleId: 'com.example.adhicine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0RSc9ykGAsuUaEMLzbmc6xUtiOqhE0dM',
    appId: '1:818624181889:web:9eb5c85100e537643fbf80',
    messagingSenderId: '818624181889',
    projectId: 'adhicine-3b5f5',
    authDomain: 'adhicine-3b5f5.firebaseapp.com',
    storageBucket: 'adhicine-3b5f5.firebasestorage.app',
    measurementId: 'G-V1NDET02J2',
  );
}
